# Generated by Django 5.2.7 on 2026-07-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_alter_category_options_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Emoji fallback shown if no image is uploaded, e.g. 🍼', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Circular category image (recommended: square, at least 150x150px)', null=True, upload_to='category_icons/')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Baby Category',
                'verbose_name_plural': 'Baby Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
