# Generated by Django 6.0.7 on 2026-07-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_product_care_instructions_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_includes',
            field=models.TextField(blank=True, help_text='List of items included with this product, separated by commas.', null=True),
        ),
    ]
